FROM continuumio/miniconda3:4.9.2-alpine

WORKDIR /app/src/

RUN conda install jupyter pip && \
    pip install rdflib==5.0.0 graph-notebook

RUN jupyter nbextension install --py --sys-prefix graph_notebook.widgets && \
    jupyter nbextension enable  --py --sys-prefix graph_notebook.widgets && \
    python -m graph_notebook.static_resources.install && \
    python -m graph_notebook.nbextensions.install

RUN python -m graph_notebook.notebooks.install --destination ./notebooks/demos

COPY ./notebooks/ ./notebooks/src/

ENTRYPOINT [ "jupyter", "notebook", "--NotebookApp.kernel_manager_class=notebook.services.kernels.kernelmanager.AsyncMappingKernelManager", "./notebooks", "--ip=*", "--port=8888", "--no-browser", "--allow-root" ]