version: '3'
services:

  server:
    build:
      args:
        VERSION: 3.5.2
    volumes:
      - /mnt/0EBC36E9BC36CACB/Data/DataSets/Candid_news/knowledge_graph:/gremlin/apache-tinkerpop-gremlin-server-3.5.2/graphs:ro

  notebooks:
    volumes:
      - /mnt/0EBC36E9BC36CACB/Data/DataSets/Candid_news/knowledge_graph:/app/src/notebooks/src/graphs:ro